# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela_escala', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escala',
            name='dia',
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_1',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_10',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_11',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_12',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_13',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_14',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_15',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_16',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_17',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_18',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_19',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_2',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_20',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_21',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_22',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_23',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_24',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_25',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_26',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_27',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_28',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_29',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_3',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_30',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_31',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_4',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_5',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_6',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_7',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_8',
            field=models.CharField(default='Folga', max_length=10),
        ),
        migrations.AddField(
            model_name='escala',
            name='dia_9',
            field=models.CharField(default='Folga', max_length=10),
        ),
    ]
