# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela_escala', '0002_auto_20170211_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.CharField(choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Marco'), ('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], max_length=2),
        ),
    ]
