# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela_escala', '0003_auto_20170218_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.CharField(choices=[('1', 'Janeiro'), ('2', 'Fevereiro'), ('3', 'Marco'), ('4', 'Abril'), ('5', 'Maio'), ('6', 'Junho'), ('7', 'Julho'), ('8', 'Agosto'), ('9', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], max_length=2),
        ),
    ]
