# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela_escala', '0005_auto_20170313_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='dia_1',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_10',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_11',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_12',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_13',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_14',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_15',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_16',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_17',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_18',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_19',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_2',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_20',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_21',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_22',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_23',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_24',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_25',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_26',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_27',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_28',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_29',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_3',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_30',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_31',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_4',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_5',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_6',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_7',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_8',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='escala',
            name='dia_9',
            field=models.CharField(choices=[('07-16', '07-16'), ('08-17', '08-17'), ('09-18', '09-18'), ('10-19', '10-19'), ('11-20', '11-20'), ('12-21', '12-21'), ('13-22', '13-22'), ('14-23', '14-23'), ('22-07', '22-07'), ('Folga', 'Folga'), ('Ferias', 'Ferias'), ('Atestado', 'Atestado'), ('Indisponivel', 'Indisponivel')], default='Indisponivel', max_length=15),
        ),
    ]
